version: 2
jobs:
  build:
    working_directory: ~/typesense-js
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@6.14'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: npm install
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: lint
          command: npm run ci-lint
      - run:
          name: test
          command: npm run ci-test
          environment:
            MOCHA_FILE: test-results/test-results.xml
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: test-results
      - store_artifacts:
          path: coverage
          destination: coverage
